### ISSUE TITLE
Sorting doesn't work properly with boolean values

### ISSUE THREAD

**Issue by rfrancisco** [hjalmers/angular-generic-table#106]
When you try to sort a column that has boolean values you get a strange behaviour and the values are not sorted correctly. To reproduce this just use the "Basic Example" and add a boolean value os just replace the lucky number with boolean values.

**Comment by rfrancisco** [comment]
As a workaround i applied added `sort: (row) => { return row.lucky_number.toString(); }` to the field configuration and now it works as expected. But it still looks like a bug.

**Comment by hjalmers** [comment]
Added a fix for this that will be part of next release:)
