### ISSUE TITLE
How to select only visible rows?

### ISSUE THREAD

**Issue by rajeshbabu91** [hjalmers/angular-generic-table#111]
Suppose a table consists of 100 rows, and we are displaying 10 rows among 100.
Clicking on "select all" should select only 10 rows, is it possible?

**Comment by hjalmers** [comment]
Hi, currently the only option would be to loop through the visible rows and pass each row to the `toggleSelect` function which is not ideal for this scenario I guess, as it might be a bit tricky to know which rows to pass if filters, search and sorting has been applied to the table as well.

Best would probably be to either have a function that specifically sets the state of visible rows (after filters, search etc has been applied) or provide a method/event for retrieving visible rows together with a function for setting the state of multiple rows. Any thoughts or preferences?

**Comment by rajeshbabu91** [comment]
Thanks Robert. solved the issue like you said by looping the visible rows and selecting it.

Great component for Angular tables and an alternative plugin for data-tables. Thank you once again for making my life easy.
