### ISSUE TITLE
Set initial state of row eg. selected or expanded

### ISSUE THREAD

**Issue by mayraGL** [hjalmers/angular-generic-table#112]
How can I select the rows that I require? I am making a catalog and I would like to load the rows that I already select previously.

**Comment by hjalmers** [comment]
It's possible but a bit cumbersome as of now so I'm going to change your question into a feature request and add the ability to set initial state of rows as well as a public function for selecting rows.

**Comment by hjalmers** [comment]
@mayra268 I'm still thinking about a nice way of handling this but in the meantime you could do the following:

```ts
    public configObject: GtConfig<RowData>;

    @ViewChild(GenericTableComponent)
    private myTable: GenericTableComponent<any, any>;

    constructor() {
        this.configObject = {
            settings: ...,
            fields: ...,
            data: ...
        };
    }

    ngOnInit() {
        setTimeout(() => {
            this.myTable.toggleSelect(this.configObject.data[1]);
        }, 0);
    }
```

This will select the second row. To select multiple rows just loop through all the rows that should be selected and pass them to the toggle select function `toggleSelect(row);`

**Comment by mayra268** [comment]
Thanks @hjalmers, i will try it

**Comment by mayraGL** [comment]
Hi @hjalmers 
You can tell me how I can get the value you send in this line 

this.myTable.toggleSelect (this.configObject.data [1]); 

Because I'm trying to do it this way but it has not worked for me.

**Comment by hjalmers** [comment]
Hi @mayraGL, I haven't had the time to come up with a nicer way of handling it but check out this [plunker](https://embed.plnkr.co/1BSiW6rfGZgBFv4zL183/), it should do the trick in the meantime:)

**Comment by hjalmers** [comment]
@mayraGL there's finally a nicer way of letting the table know the initial state for rows, take a look at  [this example](http://localhost:4200/checkbox), works the same way for normal row selection too. To set the state for expanded row use `rowExpandInitialState`.

**Comment by mayraGL** [comment]
Thanks @hjalmers. A question, the latest version supports angular 5?  I want to update it but i thinking about it.
