### ISSUE TITLE
Conditional classes added to td elements based on column value

### ISSUE THREAD

**Issue by hjalmers** [hjalmers/angular-generic-table#118]
classNames property should support functions too

**Comment by meherfattouch** [comment]
Hi, 
 Is there a rapid config to do that ? I am using generic-table and i want to just remove  classNames: 'clickable' when there is no expandedRow

**Comment by hjalmers** [comment]
Currently no, I'm not sure how you intend to use it though as the expand property is fixed at moment so if you've declared that the column can expand the row you might as well add a class like clickable at the same time?

But I'm going to create a issue for adding a class to the row when one of it's columns have expand set to true as it might be useful to know at the row level as well an not just on a particular column.

**Comment by meherfattouch** [comment]
I want to do something like that : 

**fields: [{
        name: 'Name',
        objectKey: 'name',
       // classNames: 'clickable',
        expand: true,
        render: (row) => { 
         if (row.versions.length > 0) { 
           return (`<span class="clickable">${row.versions.length > 0}${row.nom}</span>`); 
        } else { 
          return (`<span>${row.versions.length > 0}${row.nom}</span>`); 
        }
        },
      },]

**Comment by hjalmers** [comment]
Well okay, incase you don't mind where the class ends up this should work (haven't tried it myself though).

```ts
fields: [{
    name: 'Name',
    objectKey: 'name',
    expand: true,
    render: (row)=> { 
        return '<span' + (row.versions.length > 0 ? ' class="clickable"':'') + '>' + row.nom + '</span>';
    }
}]
```

**Comment by meherfattouch** [comment]
The class 'clickable' is applied for the <td> so any change inside it doesn't affect parent style. Maybe a css :has(child) can help. Will appreciate any help. Thank you

**Comment by meherfattouch** [comment]
I made some changes in css : 

tr {
  td.clickable  > span.gt-row-content > span {
    cursor: pointer;   
    text-decoration: none;
    &::before {
      content: "\f0da";
      font: normal normal normal 14px/1 FontAwesome;
      display: inline-block;
      width: 14px;
      color: #000;
    }
  }
  &.row-open {
    td.clickable > span.gt-row-content > span::before {
      content:"\f0d7"
    }
  }

and this code for the td : 

fields: [{
        name: 'Nom',
        objectKey: 'nom',
        classNames: 'clickable sort-string',
        expand: true,
        render: (row) => { 
         if (row.versions.length > 0) { 
           return (`<span class="clickable">${row.nom}</span>`); 
        } else { 
          return (`<div>${row.nom}</div>`); 
        }
      },]

Hope this help !

**Comment by hjalmers** [comment]
I see, you're using the css from the example.scss file. It's not part of generic-table and it's just meant to be an example but if you like to use you need to make some changes to the scss since you're applying the class `clickable` to the child element and not the td element:

```scss
tr {
  td span.clickable {
    cursor: pointer;
    font-weight: bold;
    color: #337ab7;
    text-decoration: none;
    &::before {
      content: "\f0da";
      font: normal normal normal 14px/1 FontAwesome;
      display: inline-block;
      width: 14px;
      color: #000;
    }
  }
}
```

**Comment by meherfattouch** [comment]
I tried your solution and it works. 
Thank you.

**Comment by hjalmers** [comment]
Since version 4.6.0 released today it's possible to use `columnClass` to add a class name to the column when a certain condition is meet, eg.

```ts
fields: [{
    name: 'Name',
    objectKey: 'name',
    expand: true,
    columnClass: (row) => {
        return row.versions.length > 0 ? 'clickable':'';
    }
}]
```
