### ISSUE TITLE
conditional inline edit

### ISSUE THREAD

**Issue by hjalmers** [hjalmers/angular-generic-table#122]
only enable inline edit if a condition is meet

**Comment by oemad** [comment]
@hjalmers hey there, any updates on this ? :smile:

**Comment by hjalmers** [comment]
Hi @oemad, I actually intended on looking at this feature during the weekend as I need it in a project I'm working on but haven't had the chance yet. Hope to post an update by the end of this week:)

**Comment by hjalmers** [comment]
@oemad there's an updated example [here](https://hjalmers.github.io/angular-generic-table/inline-editing) now. Basically inline edit property now supports passing an object with the properties `active` and `type`. Active should be a either an observable that returns a boolean (could be used to toggle inline edit) or a function that returns a boolean based on some value on the row. I've updated the wiki [here](https://github.com/hjalmers/angular-generic-table/wiki/Inline-editing) too:)
