### ISSUE TITLE
What are the styling needs to be imported for 'sort-numeric' css class

### ISSUE THREAD

**Issue by suvonkar** [hjalmers/angular-generic-table#125]
I was trying to implement a similar table like [Advanced Example](https://hjalmers.github.io/angular-generic-table/advanced). 

Could you please help me which styling is required to imported?

I am using Angular 4.

**Comment by hjalmers** [comment]
Hi @suvonkar it's not really part of generic table so you need to implement your own logic and some framework to get icons too. However feel free to copy the styles from the [example.scss](https://github.com/hjalmers/angular-generic-table/blob/master/src/examples.scss), note that it uses font-awesome so you need to include it too.

Then you need to add `.sort-numeric` class too:)

**Comment by suvonkar** [comment]
Thanks for the information.
