### ISSUE TITLE
Table object without CustomRowComponent

### ISSUE THREAD

**Issue by suvonkar** [hjalmers/angular-generic-table#127]
If I don't have any CustomRowComponent, then how can I create myTable object?

@ViewChild(GenericTableComponent)
  private myTable: GenericTableComponent<any, CustomRowComponent>;

**Comment by hjalmers** [comment]
It's just a placeholder so if you don't have a row component that you want to pass to the table just replace it with `any` like this:

```ts
@ViewChild(GenericTableComponent)
private myTable: GenericTableComponent<any, any>;
```

**Comment by suvonkar** [comment]
Thanks.
