### ISSUE TITLE
Build error when using Angular CLI --build-optimizer

### ISSUE THREAD

**Issue by jackjamieson** [hjalmers/angular-generic-table#128]
When trying to build a project that uses this library and using the flags --aot and --build-optimizer, the build breaks with error:

`ERROR in ./node_modules/rxjs/observable/BoundCallbackObservable.js`

https://github.com/angular/angular-cli/issues/7110

I think the issue is https://github.com/hjalmers/angular-generic-table/blob/master/%40angular-generic-table/core/components/generic-table.component.ts#L11

I'm not sure if it should be fixed in the library or in the CLI?

**Comment by hjalmers** [comment]
Hmm I haven't tried the ´--build-optimizer´yet so I'll have to look into it. In the meantime may I ask you what version of angular-cli and typescript you're using as it seems to be related (following the discussion in the angular-cli repo)?

**Comment by jackjamieson** [comment]
I'm on 1.3.1 for the cli and I tried typescript 2.5.x (currently on 2.5.2) like they suggested but am still getting the error.  Maybe in a newer version of the cli it is updated?

**Comment by hjalmers** [comment]
I tried now in a project that uses typescript 2.3.4 together with angular-cli 1.3.2 and angular 4.3.6 and it builds just fine without any errors so it's probably not an issue with generic-table anyways. Going to give it a try in another project on another computer too.

**Comment by jackjamieson** [comment]
@hjalmers with 1.3.2 I was able to get the build to work.  There are some other runtime errors now but at least that issue is solved!  Thanks.
