### ISSUE TITLE
Getting error "ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '0'. Current value: '3'."

### ISSUE THREAD

**Issue by suvonkar** [hjalmers/angular-generic-table#129]
I am getting an error as below:

> ERROR Error:  ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '0'. Current value: '3'. GtTableInfoComponent.html:1 

**Log:**
core.es5.js:2925 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
ajax.service.ts:25 Getting Data to Server url : http://10.208.220.114:3300/leaves
zone.js:2744 XHR finished loading: GET "http://localhost:4200/sockjs-node/info?t=1504779953732".
scheduleTask @ zone.js:2744
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:411
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:236
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2769
proto.(anonymous function) @ zone.js:1274
webpackJsonp.../../../../sockjs-client/lib/transport/browser/abstract-xhr.js.AbstractXHRObject._start @ abstract-xhr.js:132
(anonymous) @ abstract-xhr.js:21
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:425
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:192
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:499
ZoneTask.invoke @ zone.js:488
timer @ zone.js:1896
setTimeout (async)
scheduleTask @ zone.js:1906
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:411
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:236
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:1932
proto.(anonymous function) @ zone.js:1274
AbstractXHRObject @ abstract-xhr.js:20
XHRLocalObject @ xhr-local.js:8
InfoAjax @ info-ajax.js:19
webpackJsonp.../../../../sockjs-client/lib/info-receiver.js.InfoReceiver._getReceiver @ info-receiver.js:36
webpackJsonp.../../../../sockjs-client/lib/info-receiver.js.InfoReceiver.doXhr @ info-receiver.js:56
(anonymous) @ info-receiver.js:25
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:425
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:192
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:499
ZoneTask.invoke @ zone.js:488
timer @ zone.js:1896
setTimeout (async)
scheduleTask @ zone.js:1906
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:411
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:236
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:1932
proto.(anonymous function) @ zone.js:1274
InfoReceiver @ info-receiver.js:24
SockJS @ main.js:121
socket @ socket.js:7
(anonymous) @ client?ffdb:165
../../../../webpack-dev-server/client/index.js?http:/localhost:4200 @ client?ffdb:188
__webpack_require__ @ bootstrap 423621e6de58aa0ea1b3:54
0 @ main.ts:13
__webpack_require__ @ bootstrap 423621e6de58aa0ea1b3:54
webpackJsonpCallback @ bootstrap 423621e6de58aa0ea1b3:25
(anonymous) @ main.bundle.js:1
GtTableInfoComponent.html:1 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '0'. Current value: '3'.
    at viewDebugError (core.es5.js:8426)
    at expressionChangedAfterItHasBeenCheckedError (core.es5.js:8404)
    at checkBindingNoChanges (core.es5.js:8568)
    at checkNoChangesNodeInline (core.es5.js:12446)
    at checkNoChangesNode (core.es5.js:12414)
    at debugCheckNoChangesNode (core.es5.js:13191)
    at debugCheckRenderNodeFn (core.es5.js:13131)
    at Object.eval [as updateRenderer] (GtTableInfoComponent.html:1)
    at Object.debugUpdateRenderer [as updateRenderer] (core.es5.js:13113)
    at checkNoChangesView (core.es5.js:12236)
View_GtTableInfoComponent_1 @ GtTableInfoComponent.html:1
webpackJsonp.../../../core/@angular/core.es5.js.DebugContext_.logError @ core.es5.js:13415
webpackJsonp.../../../core/@angular/core.es5.js.ErrorHandler.handleError @ core.es5.js:1080
(anonymous) @ core.es5.js:4819
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:392
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ zone.js:142
webpackJsonp.../../../core/@angular/core.es5.js.NgZone.runOutsideAngular @ core.es5.js:3844
webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_.tick @ core.es5.js:4819
(anonymous) @ core.es5.js:4684
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:392
onInvoke @ core.es5.js:3890
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ zone.js:142
webpackJsonp.../../../core/@angular/core.es5.js.NgZone.run @ core.es5.js:3821
next @ core.es5.js:4684
schedulerFn @ core.es5.js:3635
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.next @ Subscriber.js:185
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._next @ Subscriber.js:125
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next @ Subscriber.js:89
webpackJsonp.../../../../rxjs/Subject.js.Subject.next @ Subject.js:55
webpackJsonp.../../../core/@angular/core.es5.js.EventEmitter.emit @ core.es5.js:3621
checkStable @ core.es5.js:3855
onLeave @ core.es5.js:3934
onInvokeTask @ core.es5.js:3884
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:424
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:192
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:499
invokeTask @ zone.js:1427
globalZoneAwareCallback @ zone.js:1445
XMLHttpRequest.send (async)
scheduleTask @ zone.js:2744
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:411
onScheduleTask @ zone.js:301
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:405
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:236
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2769
proto.(anonymous function) @ zone.js:1274
(anonymous) @ http.es5.js:1275
webpackJsonp.../../../../rxjs/Observable.js.Observable._trySubscribe @ Observable.js:171
webpackJsonp.../../../../rxjs/Observable.js.Observable.subscribe @ Observable.js:159
webpackJsonp.../../../../rxjs/operator/map.js.MapOperator.call @ map.js:54
webpackJsonp.../../../../rxjs/Observable.js.Observable.subscribe @ Observable.js:156
webpackJsonp.../../../../rxjs/operator/catch.js.CatchOperator.call @ catch.js:79
webpackJsonp.../../../../rxjs/Observable.js.Observable.subscribe @ Observable.js:156
webpackJsonp.../../../../../src/app/management/management.component.ts.ManagementComponent.getLeaveData @ management.component.ts:187
webpackJsonp.../../../../../src/app/management/management.component.ts.ManagementComponent.ngOnInit @ management.component.ts:44
checkAndUpdateDirectiveInline @ core.es5.js:10848
checkAndUpdateNodeInline @ core.es5.js:12349
checkAndUpdateNode @ core.es5.js:12288
debugCheckAndUpdateNode @ core.es5.js:13149
debugCheckDirectivesFn @ core.es5.js:13090
(anonymous) @ ManagementComponent_Host.html:1
debugUpdateDirectives @ core.es5.js:13075
checkAndUpdateView @ core.es5.js:12255
callViewAction @ core.es5.js:12620
execEmbeddedViewsAction @ core.es5.js:12578
checkAndUpdateView @ core.es5.js:12256
callViewAction @ core.es5.js:12620
execComponentViewsAction @ core.es5.js:12552
checkAndUpdateView @ core.es5.js:12261
callWithDebugContext @ core.es5.js:13475
debugCheckAndUpdateView @ core.es5.js:13015
webpackJsonp.../../../core/@angular/core.es5.js.ViewRef_.detectChanges @ core.es5.js:10181
(anonymous) @ core.es5.js:4812
webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_.tick @ core.es5.js:4812
(anonymous) @ core.es5.js:4684
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:392
onInvoke @ core.es5.js:3890
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ zone.js:142
webpackJsonp.../../../core/@angular/core.es5.js.NgZone.run @ core.es5.js:3821
next @ core.es5.js:4684
schedulerFn @ core.es5.js:3635
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.next @ Subscriber.js:185
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._next @ Subscriber.js:125
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next @ Subscriber.js:89
webpackJsonp.../../../../rxjs/Subject.js.Subject.next @ Subject.js:55
webpackJsonp.../../../core/@angular/core.es5.js.EventEmitter.emit @ core.es5.js:3621
checkStable @ core.es5.js:3855
onHasTask @ core.es5.js:3903
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.hasTask @ zone.js:445
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate._updateTaskCount @ zone.js:465
webpackJsonp.../../../../zone.js/dist/zone.js.Zone._updateTaskCount @ zone.js:289
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:209
drainMicroTaskQueue @ zone.js:602
Promise resolved (async)
scheduleMicroTask @ zone.js:585
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:414
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:236
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:256
scheduleResolveOrReject @ zone.js:842
ZoneAwarePromise.then @ zone.js:932
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._bootstrapModuleWithZone @ core.es5.js:4537
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_.bootstrapModule @ core.es5.js:4522
../../../../../src/main.ts @ main.ts:13
__webpack_require__ @ bootstrap 423621e6de58aa0ea1b3:54
0 @ main.ts:13
__webpack_require__ @ bootstrap 423621e6de58aa0ea1b3:54
webpackJsonpCallback @ bootstrap 423621e6de58aa0ea1b3:25
(anonymous) @ main.bundle.js:1
zone.js:2744 XHR finished loading: GET "http://10.208.220.114:3300/leaves".
scheduleTask @ zone.js:2744
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:411
onScheduleTask @ zone.js:301
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:405
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:236
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2769
proto.(anonymous function) @ zone.js:1274
(anonymous) @ http.es5.js:1275
webpackJsonp.../../../../rxjs/Observable.js.Observable._trySubscribe @ Observable.js:171
webpackJsonp.../../../../rxjs/Observable.js.Observable.subscribe @ Observable.js:159
webpackJsonp.../../../../rxjs/operator/map.js.MapOperator.call @ map.js:54
webpackJsonp.../../../../rxjs/Observable.js.Observable.subscribe @ Observable.js:156
webpackJsonp.../../../../rxjs/operator/catch.js.CatchOperator.call @ catch.js:79
webpackJsonp.../../../../rxjs/Observable.js.Observable.subscribe @ Observable.js:156
webpackJsonp.../../../../../src/app/management/management.component.ts.ManagementComponent.getLeaveData @ management.component.ts:187
webpackJsonp.../../../../../src/app/management/management.component.ts.ManagementComponent.ngOnInit @ management.component.ts:44
checkAndUpdateDirectiveInline @ core.es5.js:10848
checkAndUpdateNodeInline @ core.es5.js:12349
checkAndUpdateNode @ core.es5.js:12288
debugCheckAndUpdateNode @ core.es5.js:13149
debugCheckDirectivesFn @ core.es5.js:13090
(anonymous) @ ManagementComponent_Host.html:1
debugUpdateDirectives @ core.es5.js:13075
checkAndUpdateView @ core.es5.js:12255
callViewAction @ core.es5.js:12620
execEmbeddedViewsAction @ core.es5.js:12578
checkAndUpdateView @ core.es5.js:12256
callViewAction @ core.es5.js:12620
execComponentViewsAction @ core.es5.js:12552
checkAndUpdateView @ core.es5.js:12261
callWithDebugContext @ core.es5.js:13475
debugCheckAndUpdateView @ core.es5.js:13015
webpackJsonp.../../../core/@angular/core.es5.js.ViewRef_.detectChanges @ core.es5.js:10181
(anonymous) @ core.es5.js:4812
webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_.tick @ core.es5.js:4812
(anonymous) @ core.es5.js:4684
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:392
onInvoke @ core.es5.js:3890
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ zone.js:142
webpackJsonp.../../../core/@angular/core.es5.js.NgZone.run @ core.es5.js:3821
next @ core.es5.js:4684
schedulerFn @ core.es5.js:3635
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.next @ Subscriber.js:185
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._next @ Subscriber.js:125
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next @ Subscriber.js:89
webpackJsonp.../../../../rxjs/Subject.js.Subject.next @ Subject.js:55
webpackJsonp.../../../core/@angular/core.es5.js.EventEmitter.emit @ core.es5.js:3621
checkStable @ core.es5.js:3855
onHasTask @ core.es5.js:3903
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.hasTask @ zone.js:445
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate._updateTaskCount @ zone.js:465
webpackJsonp.../../../../zone.js/dist/zone.js.Zone._updateTaskCount @ zone.js:289
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:209
drainMicroTaskQueue @ zone.js:602
Promise resolved (async)
scheduleMicroTask @ zone.js:585
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:414
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:236
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:256
scheduleResolveOrReject @ zone.js:842
ZoneAwarePromise.then @ zone.js:932
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._bootstrapModuleWithZone @ core.es5.js:4537
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_.bootstrapModule @ core.es5.js:4522
../../../../../src/main.ts @ main.ts:13
__webpack_require__ @ bootstrap 423621e6de58aa0ea1b3:54
0 @ main.ts:13
__webpack_require__ @ bootstrap 423621e6de58aa0ea1b3:54
webpackJsonpCallback @ bootstrap 423621e6de58aa0ea1b3:25
(anonymous) @ main.bundle.js:1
GtTableInfoComponent.html:1 ERROR CONTEXT DebugContext_ {view: {…}, nodeIndex: 2, nodeDef: {…}, elDef: {…}, elView: {…}}component: (...)componentRenderElement: (...)context: (...)elDef: {index: 0, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, …}elOrCompView: (...)elView: {def: {…}, parent: {…}, viewContainerParent: {…}, parentNodeDef: {…}, context: NgIfContext, …}component: GtTableInfoComponent {_changeDetectionRef: ViewRef_, genericTable: GenericTableComponent}context: NgIfContext {$implicit: {…}, ngIf: {…}}def: {nodeFlags: 131, rootNodeFlags: 1, nodeMatchedQueries: 0, flags: 0, factory: ƒ, …}disposables: nullnodes: (3) [{…}, {…}, {…}]oldValues: (10) ["Showing 1 to 3 of 3 entries.", TableInfoPipe, {…}, {…}, 3, 1, 3, 3, "Loading...", "Showing  #recordFrom to #recordTo of #recordsAfter…s (filtered from a total of #recordsAll entries)."]parent: {def: {…}, parent: {…}, viewContainerParent: null, parentNodeDef: {…}, context: GtTableInfoComponent, …}parentNodeDef: {index: 1, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, …}renderer: DebugRenderer2 {delegate: BaseAnimationRenderer}root: {ngModule: NgModuleRef_, injector: OutletInjector, projectableNodes: Array(0), selectorOrNode: undefined, sanitizer: DomSanitizerImpl, …}state: 12viewContainerParent: {def: {…}, parent: {…}, viewContainerParent: null, parentNodeDef: {…}, context: GtTableInfoComponent, …}__proto__: Objectinjector: (...)nodeDef: {index: 2, parent: {…}, renderParent: {…}, bindingIndex: 1, outputIndex: 0, …}bindingFlags: 8bindingIndex: 1bindings: (9) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]childCount: 0childFlags: 0childMatchedQueries: 0directChildFlags: 0element: nullflags: 128index: 2matchedQueries: {}matchedQueryIds: 0ngContent: nullngContentIndex: -1outputIndex: 0outputs: []parent: {index: 0, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, …}provider: nullquery: nullreferences: {}renderParent: {index: 0, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, …}text: null__proto__: ObjectnodeIndex: 2providerTokens: (...)references: (...)renderNode: (...)view: {def: {…}, parent: {…}, viewContainerParent: {…}, parentNodeDef: {…}, context: NgIfContext, …}__proto__: Object
View_GtTableInfoComponent_1 @ GtTableInfoComponent.html:1
webpackJsonp.../../../core/@angular/core.es5.js.DebugContext_.logError @ core.es5.js:13415
webpackJsonp.../../../core/@angular/core.es5.js.ErrorHandler.handleError @ core.es5.js:1085
(anonymous) @ core.es5.js:4819
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:392
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ zone.js:142
webpackJsonp.../../../core/@angular/core.es5.js.NgZone.runOutsideAngular @ core.es5.js:3844
webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_.tick @ core.es5.js:4819
(anonymous) @ core.es5.js:4684
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:392
onInvoke @ core.es5.js:3890
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ zone.js:142
webpackJsonp.../../../core/@angular/core.es5.js.NgZone.run @ core.es5.js:3821
next @ core.es5.js:4684
schedulerFn @ core.es5.js:3635
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.next @ Subscriber.js:185
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._next @ Subscriber.js:125
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next @ Subscriber.js:89
webpackJsonp.../../../../rxjs/Subject.js.Subject.next @ Subject.js:55
webpackJsonp.../../../core/@angular/core.es5.js.EventEmitter.emit @ core.es5.js:3621
checkStable @ core.es5.js:3855
onLeave @ core.es5.js:3934
onInvokeTask @ core.es5.js:3884
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:424
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:192
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:499
invokeTask @ zone.js:1427
globalZoneAwareCallback @ zone.js:1445
XMLHttpRequest.send (async)
scheduleTask @ zone.js:2744
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:411
onScheduleTask @ zone.js:301
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:405
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:236
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2769
proto.(anonymous function) @ zone.js:1274
(anonymous) @ http.es5.js:1275
webpackJsonp.../../../../rxjs/Observable.js.Observable._trySubscribe @ Observable.js:171
webpackJsonp.../../../../rxjs/Observable.js.Observable.subscribe @ Observable.js:159
webpackJsonp.../../../../rxjs/operator/map.js.MapOperator.call @ map.js:54
webpackJsonp.../../../../rxjs/Observable.js.Observable.subscribe @ Observable.js:156
webpackJsonp.../../../../rxjs/operator/catch.js.CatchOperator.call @ catch.js:79
webpackJsonp.../../../../rxjs/Observable.js.Observable.subscribe @ Observable.js:156
webpackJsonp.../../../../../src/app/management/management.component.ts.ManagementComponent.getLeaveData @ management.component.ts:187
webpackJsonp.../../../../../src/app/management/management.component.ts.ManagementComponent.ngOnInit @ management.component.ts:44
checkAndUpdateDirectiveInline @ core.es5.js:10848
checkAndUpdateNodeInline @ core.es5.js:12349
checkAndUpdateNode @ core.es5.js:12288
debugCheckAndUpdateNode @ core.es5.js:13149
debugCheckDirectivesFn @ core.es5.js:13090
(anonymous) @ ManagementComponent_Host.html:1
debugUpdateDirectives @ core.es5.js:13075
checkAndUpdateView @ core.es5.js:12255
callViewAction @ core.es5.js:12620
execEmbeddedViewsAction @ core.es5.js:12578
checkAndUpdateView @ core.es5.js:12256
callViewAction @ core.es5.js:12620
execComponentViewsAction @ core.es5.js:12552
checkAndUpdateView @ core.es5.js:12261
callWithDebugContext @ core.es5.js:13475
debugCheckAndUpdateView @ core.es5.js:13015
webpackJsonp.../../../core/@angular/core.es5.js.ViewRef_.detectChanges @ core.es5.js:10181
(anonymous) @ core.es5.js:4812
webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_.tick @ core.es5.js:4812
(anonymous) @ core.es5.js:4684
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:392
onInvoke @ core.es5.js:3890
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ zone.js:142
webpackJsonp.../../../core/@angular/core.es5.js.NgZone.run @ core.es5.js:3821
next @ core.es5.js:4684
schedulerFn @ core.es5.js:3635
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.next @ Subscriber.js:185
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._next @ Subscriber.js:125
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next @ Subscriber.js:89
webpackJsonp.../../../../rxjs/Subject.js.Subject.next @ Subject.js:55
webpackJsonp.../../../core/@angular/core.es5.js.EventEmitter.emit @ core.es5.js:3621
checkStable @ core.es5.js:3855
onHasTask @ core.es5.js:3903
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.hasTask @ zone.js:445
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate._updateTaskCount @ zone.js:465
webpackJsonp.../../../../zone.js/dist/zone.js.Zone._updateTaskCount @ zone.js:289
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:209
drainMicroTaskQueue @ zone.js:602
Promise resolved (async)
scheduleMicroTask @ zone.js:585
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:414
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:236
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:256
scheduleResolveOrReject @ zone.js:842
ZoneAwarePromise.then @ zone.js:932
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._bootstrapModuleWithZone @ core.es5.js:4537
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_.bootstrapModule @ core.es5.js:4522
../../../../../src/main.ts @ main.ts:13
__webpack_require__ @ bootstrap 423621e6de58aa0ea1b3:54
0 @ main.ts:13
__webpack_require__ @ bootstrap 423621e6de58aa0ea1b3:54
webpackJsonpCallback @ bootstrap 423621e6de58aa0ea1b3:25
(anonymous) @ main.bundle.js:1

**Comment by hjalmers** [comment]
Could you please provide some more info on what you're trying to do and if possible, the markup and configuration you're using?

**Comment by suvonkar** [comment]
**My markup:**

```
        <form class="form form-inline mb-4">
          <label for="rows" class="form-control-label mr-sm-2">Rows</label>
          <select id="rows" class="form-control form-control-sm mr-sm-2 mb-3 mb-sm-0" #rowLength (change)="pendingLeaveTable.changeRowLength(rowLength.value)">
              <option value="10">10</option>
              <option value="25">25</option>
              <option value="50">50</option>
              <option value="100">100</option>
            </select>
          <input class="form-control form-control-sm mr-sm-2 mb-3 mb-sm-0" #search (keyup)="pendingLeaveTable.gtSearch(search.value)"
            placeholder="Search">
          <button class="btn btn-sm btn-primary w-100" (click)="pendingLeaveTable.exportCSV()">Export to CSV</button>
          <button class="btn btn-sm btn-primary w-100" (click)="pendingLeaveTable.expandAllRows()">Expand all</button>
          <button class="btn btn-sm btn-primary w-100" (click)="pendingLeaveTable.collapseAllRows()">Collapse all</button>

        </form>
        <div class="table-responsive">
          <generic-table #pendingLeaveTable [gtClasses]="'table-hover'" [gtSettings]="pendingLeaveTableConfigObject.settings" [gtFields]="pendingLeaveTableConfigObject.fields"
            [gtData]="pendingLeaveTableConfigObject.data" [gtRowComponent]="commentExpandRowComponent" [gtOptions]="customGtOptions"
            [gtTexts]="customGtTexts"></generic-table>
        </div>
        <div class="text-center">
          <small><gt-table-info class="form-text text-muted mb-2" [genericTable]="pendingLeaveTable" *ngIf=pendingLeaveTableConfigObject.data.length > 0></gt-table-info></small>
          <gt-pagination [gtClasses]="'pagination-sm justify-content-center'" [genericTable]="pendingLeaveTable"></gt-pagination>
        </div>
```

**My Configuration:**

```
import { GtConfig, GenericTableComponent } from '@angular-generic-table/core';

@Component({
  selector: 'management',
  encapsulation: ViewEncapsulation.None,
  templateUrl: './management.component.html',
  styleUrls: ['./management.component.css', '../angular-generic-table-cutom.css'],
  providers: [AjaxService, DatePipe]
})
export class ManagementComponent implements OnInit {
public pendingLeaveTableConfigObject: GtConfig<any>;
public customGtOptions: any = {stack:true, highlightSearch:true, csvDelimiter:','};
  public customGtTexts: any = {noData:'No data found'};
@ViewChild(GenericTableComponent)
  private pendingLeaveTable: GenericTableComponent<any, CommentRowComponent>;
  commentExpandRowComponent = CommentRowComponent;

constructor(private ajaxService: AjaxService, private datePipe: DatePipe, public snackBar: MdSnackBar) { }

ngOnInit(): void {
    this.pendingLeaveConfigureTableConfigObj();
    this.getLeaveData();
  }

private pendingLeaveConfigureTableConfigObj(): any {

    let that: ManagementComponent = this;

    this.pendingLeaveTableConfigObject = {
      settings: [{
        objectKey: 'employeeName'
      }, {
        objectKey: 'employeeEmail'
      }, {
        objectKey: 'leaveTypeType'
      }, {
        objectKey: 'from'
      }, {
        objectKey: 'to'
      }, {
        objectKey: 'count'
      }, {
        objectKey: 'approve_action',
        sort: 'disable',
        search: false
      }, {
        objectKey: 'reject_action',
        sort: 'disable',
        search: false
      }],
      fields: [{
        name: 'Employee Name',
        objectKey: 'employeeName',
        columnClass: 'sort-string expandable',
        expand: true,
        value: (row) => { return row.employee.name }
      }, {
        name: 'Employee Email',
        objectKey: 'employeeEmail',
        columnClass: 'sort-string',
        value: (row) => { return row.employee.email },
        render: function (row) { return '<a href="mailto:' + row.employee.email + '">' + row.employee.email + '</a>'; }
      }, {
        name: 'Leave Type',
        objectKey: 'leaveTypeType',
        columnClass: 'sort-string',
        value: (row) => { return row.leaveType.type }
      }, {
        name: 'From',
        objectKey: 'from',
        export: function (row) { return that.datePipe.transform(row.from, AppConstant.DD_MON_YY_DATE_FORMAT); },
        render: function (row) { return that.datePipe.transform(row.from, AppConstant.DD_MON_YY_DATE_FORMAT); },
        columnClass: 'sort-amount'
      }, {
        name: 'To',
        objectKey: 'to',
        export: function (row) { return that.datePipe.transform(row.to, AppConstant.DD_MON_YY_DATE_FORMAT); },
        render: function (row) { return that.datePipe.transform(row.to, AppConstant.DD_MON_YY_DATE_FORMAT); },
        columnClass: 'sort-amount'
      }, {
        name: 'Day(s)',
        objectKey: 'count',
        columnClass: 'sort-numeric'
      }, {
        name: '',
        objectKey: 'approve_action',
        value: () => '',
        render: function (row) { return '<button type="button" class="btn btn-success">Approve</button>'; },
        click: (row) => { this.approveLeave(row); }
      }, {
        name: '',
        objectKey: 'reject_action',
        value: () => '',
        render: function (row) { return '<button type="button" class="btn btn-danger">Reject</button>'; },
        click: (row) => { this.rejectLeave(row); }
      }],
      data: []
    }
  }
}
```

Please note this is not the whole code. I am sharing just the small portion of the code associated with GenericTable.

**Comment by suvonkar** [comment]
Possible solution is [here](https://stackoverflow.com/a/34364881/352043)

**Comment by hjalmers** [comment]
Hi @suvonkar, I haven't had the chance to look at your code but it's a pretty common error which occurs when you're updating or altering something after the view has been rendered. This is solved by making sure you're updating objects or entities at the right time in the lifecycle process, another solution might in some case be to wrap the altering function inside a timeout to trigger and execute the function during the next life cycle "loop". Since you closed the issue I take it you found a solution to your problem:)
