### ISSUE TITLE
How to add checkbox in table fields name?

### ISSUE THREAD

**Issue by hmahmed91** [hjalmers/angular-generic-table#132]
fields: [
      {
          objectKey: 'edit', name: '', // I want to add check box here like objectKey: 'edit', name: 'input type checkbox',
          value: () => '',
          render: (row) => this.renderCheckBoxes(row.id),
          click: (row) => this.editService.click(row.id)
        },
        {
        name: 'Id',
        objectKey: 'id'
      }, {
        name: 'Name',
        objectKey: 'name',
        inlineEdit: true,
        showSearchIcon:true
      },

**Comment by hjalmers** [comment]
Hi @hmahmed91, there are different ways to implement checkboxes with generic table, one would be to use styling like in this [plunker](https://embed.plnkr.co/XPWjIZE0X3iHhI1HuGO1/), although I have to admit it's a bit hacky and that's why I've created issue #96, but you could create your own custom component too. I'm going to close this as a duplicate so please follow #96 to keep track of the status.

**Comment by hmahmed91** [comment]
Thanks for the response and I follow "[add checkbox toggle #96](https://github.com/hjalmers/angular-generic-table/issues/96)"

**Comment by hijoncon** [comment]
@hjalmers I am trying to add the checkbox in the name field. Do you have an idea how to implement that?

**Comment by hjalmers** [comment]
@hijoncon, when you're saying the name field are you referring to the table header, or more precise, what ends up in the table header?

**Comment by hijoncon** [comment]
@hjalmers yes the table header, I wanted to inject a checkbox there that can do toggle check/uncheck all row checkbox. Any idea? Thanks in advance!

**Comment by hjalmers** [comment]
Currently it's not possible but that's one of the goals with #96. You could add a checkbox outside the table and use absolute position to make it look like it's part of the  table header and use the functions to select/deselect all rows in the meantime.

**Comment by hijoncon** [comment]
Ok sounds good. Thanks for the response. Looking forward to the next release!

**Comment by anivaisu** [comment]
Hi @hjalmers.I added check box outside the table .How can i set select/deselect rows tables.Give me some idea.
