### ISSUE TITLE
Add support for drill down using same structure and keep width of parent

### ISSUE THREAD

**Issue by hjalmers** [hjalmers/angular-generic-table#137]

**Comment by beerran** [comment]
Will we be able to show underlying data using this, eg. have 40 rows which sums up to the drilldown row, and then expand these while preserving column widhts/visibility/ordering?

**Comment by hjalmers** [comment]
@beerran yes, that's the idea. Currently you can get the width of all the columns and access them including the config from the `GtExpandingRow` component. So you could basically use that info and build your own component to handle the logic and layout for the nested table/component, i.e fetch details using a service and so on.

The goal however is to provide a component that does all this for you. I've actually created a component to prove the concept and it works great, I just need to finalize the example and figure out a nice way of letting the nested table know what data it should use.

Currently it works with data objects like this, note that you'd have to provide the details in the data and also let the component know that `details` holds the data for the nested row. Would be nice to let the user provide a service to fetch the details too so I'm going to think about it so more. But hopefully it will be part of the next release:)

```json
[  
   {  
      "row":"1",
      "id":"fruits",
      "quantity":"20",
      "details":[  
         {  
            "row":"1",
            "id":"apples",
            "quantity":"15"
         },
         {  
            "row":"2",
            "id":"bananas",
            "quantity":"5"
         }
      ]
   },
   {  
      "row":"2",
      "id":"vegetables",
      "quantity":"10",
      "details":[  
         {  
            "row":"1",
            "id":"carrots",
            "quantity":"10"
         }
      ]
   }
]
```
