### ISSUE TITLE
Is there any way to set the 'numberOfRows' value as 'ALL' to show all data when table is initiated?

### ISSUE THREAD

**Issue by suvonkar** [hjalmers/angular-generic-table#138]
Is there any way to set 'numberOfRows' value as **ALL** to show all data when table is initiated?

Basically I don't need pagination and I want to show all the data in table at a time.

**Comment by hjalmers** [comment]
Currently no, you'll have to either set the number of row to a really high number that is greater than the number of rows you'll ever need to render or set to number of visible rows to be equal to the number of rows in your data. I've created a separate issue #139 for this though as I know it's needed and useful, so I'm closing this as it will be fixed/added with #139:)
