### ISSUE TITLE
render method not drawing dom element

### ISSUE THREAD

**Issue by cdanyl** [hjalmers/angular-generic-table#140]
Hello!
Using version "@angular-generic-table/core": "^4.6.0, i setting up my fields with a render method that return just a simple DOM element like a button.
```
{
   name: '',
   objectKey: 'action',
   render: () => '<button type="button" class="btn btn-outline-primary btn-sm">Edit</button>',
   value: () => '',
}
```
In my view, nothing appear to be rendered, the chrome inpector show me an empty span
`<span class="gt-row-content"></span>`

I follow exactly the `https://hjalmers.github.io/angular-generic-table/custom-column`example.

any idea ?

**Comment by cdanyl** [comment]
I found :) the property `data` of `GtConfig` must be initialized with empty array

**Comment by hjalmers** [comment]
Yeah that’s true, should add it to docs or perhaps even better, change it so it would work without specifying an empty array.

**Comment by avril-verhaeghen** [comment]
I'm having the same issue with version 4.8.0, but like @cdanyl said, I initialized `data` of `GtConfig` with an empty array, insert data later within in Promise but still renders nothing, not even going in the render function (console log in it and doesn't log).

My code in the constructor:
`this.gtConfig = {
      settings: [
        {
          objectKey: 'name',
          sort: 'asc',
          columnOrder: 0
        }, {
          objectKey: 'priority',
          sort: 'asc',
          columnOrder: 1
        }
      ],
      fields: [
        {
          name: 'Name',
          objectKey: 'name'
        }, {
          name: 'Prioriteit',
          objectKey: 'priority',
          render: () => 'hello'
        }
      ],
      data: []
    };`

Then I trigger a "getData" method in `ngOnInit`

`private _getData() {
    this.myService.getNames().then(data => {
      this.gtConfig.data = data['content'];
    });
  }`

Data is array containing the objects for the table.

Anyone got some suggestions?

For info, I use the same exact method in another page of the same app and there it renders correctly.
