### ISSUE TITLE
Filter / Search to API ?

### ISSUE THREAD

**Issue by rullymartanto** [hjalmers/angular-generic-table#143]
Hi It's great table 

How if I want to search or Filter  POST to API Point ?
I have read this code 
public trigger = function($event){
    if ($event.value && $event.value.selectedRows) {
      this.selectedRows = $event.value.selectedRows.length;
    }
  };

and do this

this.http.post(this.url, req)
        .subscribe(res => {
          this.configObject.data = res.data;
        });

But not really sure how to POST request to API and get return data
Thanks

**Comment by hjalmers** [comment]
Hi @rullymartanto, if I'm understanding your question correctly you want to filter / search server-side and update the data in the table right? Have you looked at the [lazy loading](https://hjalmers.github.io/angular-generic-table/lazy) example? Should probably look into updating it and use the new HttpClientModule instead but the concept is still valid, just add the filter/search info to your request body.

**Comment by rullymartanto** [comment]
Yes, Exactly,.. 
Many thanks @hjalmers

**Comment by hjalmers** [comment]
I've also added a section in the wiki [here](https://github.com/hjalmers/angular-generic-table/wiki/Lazy-loading-and-table-info) with some more info related to this issue:)
