### ISSUE TITLE
Getting a value from component

### ISSUE THREAD

**Issue by Liahus1996** [hjalmers/angular-generic-table#145]
I want to get a value from component and use it for navigation path , but am not able to get any values other than the row values , What can i do in this case ?

```
render: function (row) {
        this.someotherValue;
        return '<a href='/path1/'+ _this.someotherValue_ +'/'+ row.id +'>' + row.id + `</a>`; }
      }
```

this.someotherValue should get values from my Component #

**Comment by hjalmers** [comment]
Try using an arrow function instead ex. instead of:

```
render: function (row) {
        this.someotherValue;
        return '<a href='/path1/'+ _this.someotherValue_ +'/'+ row.id +'>' + row.id + '</a>';
      }
```

Do:

```ts
render: (row)=> '<a href='/path1/'+ _this.someotherValue_ +'/'+ row.id +'>' + row.id + '</a>'
```

**Comment by Liahus1996** [comment]
It works :) many thanks

**Comment by Liahus1996** [comment]
Can we add angular specific values like routerLink instead of href  ?
