### ISSUE TITLE
Export CSV and support utf-8

### ISSUE THREAD

**Issue by Paul75** [hjalmers/angular-generic-table#147]
Hello,

In the table I have a carater 'à', 'é' or another and in export it not appear ?

What can I do ?

Thanks

**Comment by hjalmers** [comment]
This is a bug, will look into adding support for utf-8

**Comment by Paul75** [comment]
Hello,

Also I I do a (click)="myTable.exportCSV('Export_GOMPOST_datas')" in my Mac it export file with extention but in windows firefox for exemple I must do : (click)="myTable.exportCSV('Export_GOMPOST_datas.csv')"

Normal ?

**Comment by hjalmers** [comment]
Sounds like a potential bug, will look into it:)

**Comment by hjalmers** [comment]
Hi @Paul75, I think this should be working now if you enable BOM, at least it works for me on windows. I gave it a try on my mac too and the file is exported correctly but Excel 2011 (which I'm using) have a hard time handling utf-8 not sure how it is with the never version though. BOM is off by default but you can enable it by passing true as a second parameter to the export method like this:
```js
myTable.exportCSV('Export_GOMPOST_datas', true)
```
There was a bug which caused the file extension to not appear on some platforms when using custom file name but it should work now too. Please give it a try and let me know:)

**Comment by Paul75** [comment]
It seem solve the bug :) great works :)
