### ISSUE TITLE
Customize date format in field

### ISSUE THREAD

**Issue by Paul75** [hjalmers/angular-generic-table#148]
Hello,

In fields I have : 
`{
        name: 'Date de création',
        objectKey: 'createdAt'
      }`

I want to format this date to dd-MM-YYYY for exemple ?

When I can do ?

Thanks

**Comment by Paul75** [comment]
Hello,

Found with di this but not think if is good : 
`new Date(row.createdAt).toLocaleDateString()`

Thanks

**Comment by hjalmers** [comment]
Hi Paul, not sure how or where you're getting/creating the date but check out [this plunker ](https://embed.plnkr.co/UIlaMDag8vSNAhLVtnvQ/) for an idea on how you can use the built in [DatePipe](https://angular.io/api/common/DatePipe) to format dates.

**Comment by Paul75** [comment]
Thanks :)

Soved question :)
