### ISSUE TITLE
Error in execution your zip

### ISSUE THREAD

**Issue by Paul75** [hjalmers/angular-generic-table#150]
Hello,

I download package and in console do npm install -> OK install
After I do npm start and then it error : 
`ERROR in ./@angular-generic-table/core/components/gt-dropdown.component.ts
Module not found: Error: Can't resolve 'tether' in '/Users/far-paul/Sites/angular-generic-table/@angular-generic-table/core/components'
resolve 'tether' in '/Users/far-paul/Sites/angular-generic-table/@angular-generic-table/core/components'
  Parsed request is a module
  using description file: /Users/far-paul/Sites/angular-generic-table/@angular-generic-table/core/package.json (relative path: ./components)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/far-paul/Sites/angular-generic-table/@angular-generic-table/core/package.json (relative path: ./components)
    resolve as module
      /Users/far-paul/Sites/angular-generic-table/@angular-generic-table/core/components/node_modules doesn't exist or is not a directory
      /Users/far-paul/Sites/angular-generic-table/@angular-generic-table/core/node_modules doesn't exist or is not a directory
      /Users/far-paul/Sites/angular-generic-table/@angular-generic-table/node_modules doesn't exist or is not a directory
      /Users/far-paul/Sites/node_modules doesn't exist or is not a directory
      /Users/far-paul/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/far-paul/Sites/angular-generic-table/node_modules
        using description file: /Users/far-paul/Sites/angular-generic-table/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/far-paul/Sites/angular-generic-table/package.json (relative path: ./node_modules)
          using description file: /Users/far-paul/Sites/angular-generic-table/package.json (relative path: ./node_modules/tether)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/far-paul/Sites/angular-generic-table/node_modules/tether doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/far-paul/Sites/angular-generic-table/node_modules/tether.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/far-paul/Sites/angular-generic-table/node_modules/tether.js doesn't exist
            as directory
              /Users/far-paul/Sites/angular-generic-table/node_modules/tether doesn't exist
      looking for modules in /Users/far-paul/Sites/angular-generic-table/node_modules
        using description file: /Users/far-paul/Sites/angular-generic-table/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/far-paul/Sites/angular-generic-table/package.json (relative path: ./node_modules)
          using description file: /Users/far-paul/Sites/angular-generic-table/package.json (relative path: ./node_modules/tether)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/far-paul/Sites/angular-generic-table/node_modules/tether doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/far-paul/Sites/angular-generic-table/node_modules/tether.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/far-paul/Sites/angular-generic-table/node_modules/tether.js doesn't exist
            as directory
              /Users/far-paul/Sites/angular-generic-table/node_modules/tether doesn't exist
      looking for modules in /Users/far-paul/Sites/angular-generic-table/src
        using description file: /Users/far-paul/Sites/angular-generic-table/package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/far-paul/Sites/angular-generic-table/package.json (relative path: ./src)
          using description file: /Users/far-paul/Sites/angular-generic-table/package.json (relative path: ./src/tether)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/far-paul/Sites/angular-generic-table/src/tether doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/far-paul/Sites/angular-generic-table/src/tether.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/far-paul/Sites/angular-generic-table/src/tether.js doesn't exist
            as directory
              /Users/far-paul/Sites/angular-generic-table/src/tether doesn't exist
      looking for modules in /Users/far-paul/Sites/angular-generic-table/src
        using description file: /Users/far-paul/Sites/angular-generic-table/package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/far-paul/Sites/angular-generic-table/package.json (relative path: ./src)
          using description file: /Users/far-paul/Sites/angular-generic-table/package.json (relative path: ./src/tether)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/far-paul/Sites/angular-generic-table/src/tether doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/far-paul/Sites/angular-generic-table/src/tether.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/far-paul/Sites/angular-generic-table/src/tether.js doesn't exist
            as directory
              /Users/far-paul/Sites/angular-generic-table/src/tether doesn't exist
[/Users/far-paul/Sites/angular-generic-table/@angular-generic-table/core/components/node_modules]
[/Users/far-paul/Sites/angular-generic-table/@angular-generic-table/core/node_modules]
[/Users/far-paul/Sites/angular-generic-table/@angular-generic-table/node_modules]
[/Users/far-paul/Sites/node_modules]
[/Users/far-paul/node_modules]
[/Users/node_modules]
[/node_modules]
[/Users/far-paul/Sites/angular-generic-table/node_modules/tether]
[/Users/far-paul/Sites/angular-generic-table/node_modules/tether.ts]
[/Users/far-paul/Sites/angular-generic-table/node_modules/tether.js]
[/Users/far-paul/Sites/angular-generic-table/node_modules/tether]
[/Users/far-paul/Sites/angular-generic-table/node_modules/tether]
[/Users/far-paul/Sites/angular-generic-table/node_modules/tether.ts]
[/Users/far-paul/Sites/angular-generic-table/node_modules/tether.js]
[/Users/far-paul/Sites/angular-generic-table/node_modules/tether]
[/Users/far-paul/Sites/angular-generic-table/src/tether]
[/Users/far-paul/Sites/angular-generic-table/src/tether.ts]
[/Users/far-paul/Sites/angular-generic-table/src/tether.js]
[/Users/far-paul/Sites/angular-generic-table/src/tether]
[/Users/far-paul/Sites/angular-generic-table/src/tether]
[/Users/far-paul/Sites/angular-generic-table/src/tether.ts]
[/Users/far-paul/Sites/angular-generic-table/src/tether.js]
[/Users/far-paul/Sites/angular-generic-table/src/tether]
 @ ./@angular-generic-table/core/components/gt-dropdown.component.ts 12:0-33
 @ ./@angular-generic-table/core/core.module.ts
 @ ./@angular-generic-table/core/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts`

Why ?

**Comment by hjalmers** [comment]
Looks you’re missing tether which is used for positioning the inline edit dropdown component. It’s listed as a dependency so npm should have downloaded it too but make sure you have tether in your node_modules folder.

**Comment by Paul75** [comment]
I donwload the github and npm install and npm start ....

**Comment by hjalmers** [comment]
Okay are you trying to run the project locally?

**Comment by Paul75** [comment]
of course it locally ....

**Comment by hjalmers** [comment]
I see, I'll try to set up a wiki article on how to run the project locally:)

**Comment by Avirup1** [comment]
link to that wiki ?

**Comment by hjalmers** [comment]
Sorry for the late reply @Avirup1, you should just have to clone the repository and run npm start...

**Comment by helmerfuentes** [comment]
ERROR in The target entry-point "@angular-generic-table/core" has missing dependencies:
 - tether
