### ISSUE TITLE
Angular 5 warning ...

### ISSUE THREAD

**Issue by Paul75** [hjalmers/angular-generic-table#151]
Hello,

In Angular 5.0.1 I've got : 

`npm WARN @angular-generic-table/core@4.7.1 requires a peer of @angular/core@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular-generic-table/core@4.7.1 requires a peer of @angular/common@^4.0.0 but none is installed. You must install peer dependencies yourself.`

It pose problem ? works good or not compatible with Angular 5 ?

Thansk

**Comment by hjalmers** [comment]
It works as per #149 :)
