### ISSUE TITLE
Stacking doesn't work for me 

### ISSUE THREAD

**Issue by Liahus1996** [hjalmers/angular-generic-table#155]
I have tried setting the stack:true but even though the css is present it is not performing the expected action

**Comment by hjalmers** [comment]
Can you post your code or maybe provide a plunker? https://embed.plnkr.co/zdJBXKRvEv7FbkzEDbeE/

**Comment by Liahus1996** [comment]
Here's my code , whenever stack:true is given my column header is appended along with the value and responsiveness is not working

`<gt-column-settings [genericTable]="configObject.data" #columnSettings>
                                <div class="table-responsive pos-rel">
                                    <generic-table [gtClasses]="'table-hover table-sm table table-grey-border'" #myTable [gtSettings]="configObject.settings" [gtFields]="configObject.fields"
                                        [gtData]="configObject.data" [gtInfo]="configObject.info" [gtOptions]="{lazyLoad:true, rowSelection:true,stack:true,highlightSearch:true}"
                                        (gtEvent)="trigger(currentOrderType,$event)" [gtTexts]="{loading:'',noData:'Data is not available'}"></generic-table>
                                </div>
                                <div class="text-center">
                                    <gt-pagination [gtClasses]="'justify-content-center'" [genericTable]="myTable"></gt-pagination>
                                </div>
                            </gt-column-settings>`

**Comment by Liahus1996** [comment]
Which CSS file should I use specifically to do so ? Since am not able to use css values imported from package

**Comment by hjalmers** [comment]
Okay, it sounds like it's working as expected then. When stacking is enabled it will actually add the labels to the columns and turn them into rows instead but you need to either load the provided css/scss for generic table or write your own custom css.

Are you using angular-cli?

If so I would recommend using scss (sass) for styling and then simply add to your root `styles.scss` the following:

```scss
@import '~@angular-generic-table/core/scss/generic-table';
```

If you want to stick with css, you need to add it to your `.angular-cli.json` file under styles:

```json
styles: [
    "../node_modules/@angular-generic-table/core/css/generic-table.css",
    "styles.css"
],
```

**Comment by Liahus1996** [comment]
It Works perfectly :)
