### ISSUE TITLE
Append tootltip to column header

### ISSUE THREAD

**Issue by Liahus1996** [hjalmers/angular-generic-table#158]
How do i add a question mark tooltip to the Column header ? I tried several possibilities but the tags are displayed as it is in screen

**Comment by Liahus1996** [comment]
Any idea as to how we can try this ?

**Comment by hjalmers** [comment]
Currently it would be a bit tricky, it's pretty easy to just add the appearance but it's another thing to get the behavior of a tool-tip. I'll mark this a s a feature request as I think it's something we should support but I can't say when I'll have time to look at it.

**Comment by Liahus1996** [comment]
How to add the appearance at least ? since am not gonna use jquery to append a span with "?" symbol . I want to achieve it the Angular way

**Comment by Liahus1996** [comment]
Any idea as to how we can access the header and modify them ? I know columnComponent is there to achieve it for column values , is there something like that for header too ?

**Comment by hjalmers** [comment]
Hi, sorry for the late reply. This feature will part of next release which I hope will be released in a few days:)

**Comment by Liahus1996** [comment]
Thanks :)

**Comment by hjalmers** [comment]
feature available in v4.9.0, checkout [this example](https://hjalmers.github.io/angular-generic-table/custom-header)

**Comment by Liahus1996** [comment]
Thanks mate ! does it facilitate localization ?
