### ISSUE TITLE
Integration with PrimeNG

### ISSUE THREAD

**Issue by Paul75** [hjalmers/angular-generic-table#160]
Hello,

Is simple to integrate for exemple add new line, edit, remove with the plugin PrimeNG ?

Thanks

**Comment by hjalmers** [comment]
Should be fairly simple, in fact we used it before too for some other projects together with generic table but opted for [ng-bootstrap](https://ng-bootstrap.github.io/#/home) instead which I personally prefer over ng-prime. Take a look at #124 it should give you a hint on how to move forward, that example uses ng-bootstrap but you could use whatever you like really. Just make sure to add the component as an entryComponent to you module.

**Comment by Paul75** [comment]
hello,

But PrimeNG contain more element than ng-bootstrap ? no ?

**Comment by hjalmers** [comment]
True, but then again do you need them all? I personally think ng-bootstrap has a better implementation, but like I said before you can use any component you like together with generic table even though some might be easier and work better with how things are implemented in this table.
