### ISSUE TITLE
Changing Sort behaviour

### ISSUE THREAD

**Issue by Liahus1996** [hjalmers/angular-generic-table#162]
How to start with DESC sort instead of the ASC sort initially when the sorting icon is first clicked ?

**Comment by hjalmers** [comment]
@Liahus1996 it will always cycle between unsorted, sort ascending and sort descending when clicking a header, i.e if you [set the initial sorting](https://github.com/hjalmers/angular-generic-table/wiki/Configuration) to be descending the next time you click it should be unsorted. However it doesn’t really make sense to go back to a unsorted state in most cases so it will then just switch between ascending and descending unless you click on another header witch will then start with ascending. Does that make sense? It might be that we want to enable a different behavior too but that’s how it works right now at least:)

**Comment by Liahus1996** [comment]
Ya understood , Thanks
