### ISSUE TITLE
Issue with Pipes

### ISSUE THREAD

**Issue by Liahus1996** [hjalmers/angular-generic-table#163]
Am currently using Pipes to format my currencies within the render function , though it works perfectly on screen but when i export as PDF or Excel , the value before i applied pipes are getting displayed

**Comment by hjalmers** [comment]
I take it you found the export function in the [configuration](https://github.com/hjalmers/angular-generic-table/wiki/Configuration) @Liahus1996 which is the way to handle how to export the field?
