### ISSUE TITLE
Localization text are displayed but getting error

### ISSUE THREAD

**Issue by Liahus1996** [hjalmers/angular-generic-table#166]
Am currently trying out localization in data table which is not specific to data table alone but for whole page. When i load the page the translated text is displayed but am getting 
`ERROR TypeError: Cannot read property 'data' of undefined`
Then the whole page functionality is disturbed.  How could i avoid this ?

**Comment by Liahus1996** [comment]
And also am not having a static data , am getting data via ngOnInit()

**Comment by SangiliMuthu** [comment]
I have similar doubt regarding Localization...

Localization key words mentioned in "https://hjalmers.github.io/angular-generic-table/localization" are predefined or you configured those some where and referring those?.

If you configured keys manually, You configured keys for data as well?

Thanks in advance.

**Comment by hjalmers** [comment]
@Liahus1996 and @SangiliMuthu are you both using ngx-translate? I think you might have two separate issues/questions but to answer your question first @Liahus1996, it's hard to say without being able to see the code but generic-table isn't doing anything specific in terms of localisation/translations. My guess is that you're initiating the table before the translations have loaded, either load an empty setup that you change when you have the translations or put a condition on the table (like *ngIf) so it's only initiated when you have translations. If you could provide a plunker with some code I could take a look at it:) The example I've provided is only one way of implementing localisation but there are other setups too that might suit your needs better.  

Not sure I got your question @SangiliMuthu, but in my example I'm using static files loaded over http for the translations, but you could use an REST-api or whatever really. Below is an example of how ngx-translate is setup for the example.

```ts
import { TranslateModule, TranslateLoader} from '@ngx-translate/core';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';

export function createTranslateLoader(http: HttpClient) {
    return new TranslateHttpLoader(http, './assets/i18n/', '.json');
}

@NgModule({
    declarations: [
        ...
    ],
    imports: [
        ...
        TranslateModule.forRoot({
            loader: {
                provide: TranslateLoader,
                useFactory: (createTranslateLoader),
                deps: [HttpClient]
            }
        })
    ],
    bootstrap: [AppComponent]
})
export class AppModule { }
```

Regarding keys for the data, I guess it depends on the data but you'll probably have it in some database somewhere and you probably just want to store the raw data and not the translation keys and perhaps do the translation server-side so you ask for the data in a specific language when you fetch the data to the table. But again, it's really hard to say as it might differ depending on your specific use case.

**Comment by SangiliMuthu** [comment]
Thanks for the quick reply.

I understood the things :)

**Comment by Liahus1996** [comment]
I have gone with the empty setup mate ! Works fine
