### ISSUE TITLE
Select only visible rows (after search)

### ISSUE THREAD

**Issue by Helmi-helmutson** [hjalmers/angular-generic-table#171]
I'm trying to create a button to select only the rows wich are displayed after a search. How can i achieve this. 
Or for the start, how can i access only the displayed rows?
I know that if i search i get an "gt-info" event wich has a property "recordsAfterSearch" wich shows the count of the displayed rows but not its values. 

Can anyone help ?

**Comment by hjalmers** [comment]
It's a good question, the only way to achieve it now would be to implement your own logic (which could be the same as the one built into the table) to filter all records. It's not a nice solution really so I'm going to add this is a feature request and initially I think the easiest solution would be to expose the rows on the gt-info object passed with the event, which you then could use to select them or whatever one might want to do.

**Comment by Helmi-helmutson** [comment]
That's what i thougth, somehow publish it in gt-info. How long would that take to implement it, i really need that features as soon as possible, and I can't really achieve it by myself. I'm pretty new to Angular and TypeScript, maybe you could give me some advise how and where to start to implement this feature?

**Comment by hjalmers** [comment]
@Helmi-helmutson I've added `visibleRecords` to gt-info so it will be available with the next release which I hope will be released pretty soon.

**Comment by Helmi-helmutson** [comment]
Awesome!!! Thx!
If you ever get to nuremberg Beer is on me :-)

**Comment by hjalmers** [comment]
@Helmi-helmutson will keep that in mind:) I've release v4.10.0 now so feel free to give it a try:)
