### ISSUE TITLE
Error method expandAllRows

### ISSUE THREAD

**Issue by mayraGL** [hjalmers/angular-generic-table#172]
I am executing method **this.myTable.expandAllRows()** when i click on a button immediately after the table is displayed but its throw the following error when trying to expand all the rows.

![captura](https://user-images.githubusercontent.com/29493115/34387354-4867fc04-eaf3-11e7-9e9d-cf968be8ae40.PNG)

this is my markup

![captura1](https://user-images.githubusercontent.com/29493115/34387796-cb13569c-eaf5-11e7-9c04-88a89616e921.PNG)

![captura2](https://user-images.githubusercontent.com/29493115/34387801-d095dac2-eaf5-11e7-905c-f8b8dc4e8cd5.PNG)

this is the table configuration

![captura3](https://user-images.githubusercontent.com/29493115/34387806-df079d8e-eaf5-11e7-8e44-c2232d98c44f.PNG)

![captura4](https://user-images.githubusercontent.com/29493115/34387808-e09d2736-eaf5-11e7-87f4-5c2e15e013e2.PNG)

**Comment by Helmi-helmutson** [comment]
Werde and how do you assign the data to the table?

**Comment by mayraGL** [comment]
In event ngOnInit() I call the method that assings settings, after that call the method that assings the fields with her traduction y then call the method that call the web service to obtain the data

![captura](https://user-images.githubusercontent.com/29493115/34499472-d3a10e14-efcb-11e7-9301-311788e63737.PNG)

**Comment by hjalmers** [comment]
Hi, sorry for the late reply. I just realised that some of the examples where not updated and that the wiki didn't mention anything about the new options that are available so please take a look at this
[example](https://hjalmers.github.io/angular-generic-table/row-selection) (it's for row selection but just change from `rowSelectionInitialState` to `rowExpandInitialState` to make it work with expanding rows). The options are also described [here](https://github.com/hjalmers/angular-generic-table/wiki/Options) now.

**Comment by mayraGL** [comment]
No @hjalmers , I'm trying to expand all rows with the method expandAllRows() when the user click on a button

![image](https://user-images.githubusercontent.com/29493115/34833715-b4ba31d8-f6b5-11e7-9c48-9d0a3c1a6ec2.png)

Already set the GtOptions and expand property in the field

![image](https://user-images.githubusercontent.com/29493115/34833825-fa682b7c-f6b5-11e7-9cc0-32529a5782af.png)

![image](https://user-images.githubusercontent.com/29493115/34833890-1f75e15c-f6b6-11e7-9620-683985f83bed.png)

But when i call the method expandAllRows() throws me an error in the GenericTableComponent.html, line 83

![image](https://user-images.githubusercontent.com/29493115/34834000-6bc200cc-f6b6-11e7-88cf-257c17fa6b97.png)

![image](https://user-images.githubusercontent.com/29493115/34834072-989fe9e2-f6b6-11e7-9176-73891df70b02.png)

**Comment by hjalmers** [comment]
I see, it might be related to #175, but another thing I noticed is that you're just passing `(row) => row` to your DetalleUsarioComponent here:

```ts
expand: {
     component: DetalleUsarioComponent,
     data: (row) => row // this line is unnecessary as row is passed by default 
}
``` 

It shouldn't break the code but try removing that line. I think there's some issue with the expand/collapse all function so I´ll look into it and update the example. Your issue might be something else though...

**Comment by hjalmers** [comment]
I noticed that the collapse/expand all function wasn't working unless at least one row had been toggled before. As the table now support expanding different components (one per column), we now need to tell it which component we want to show when expanding all rows without using the specific settings from a column. See updated and working example [here](https://hjalmers.github.io/angular-generic-table/advanced) for an example on how to call the function and pass that information to the table. It should solve your problem @mayraGL I hope:)

**Comment by mayraGL** [comment]
Thanks @hjalmers , it work perfect!!! 💯 👍

**Comment by hjalmers** [comment]
Glad to hear it worked and thanks for reporting the issue @mayraGL:) I’ll close this issue now:)
