### ISSUE TITLE
render: (row) not working when data inserted inside a subscription

### ISSUE THREAD

**Issue by jackjamieson** [hjalmers/angular-generic-table#176]
I have a table getting data from a REST call just like the example shows, but when I add the data from inside the REST call it looks like the configuration for the fields array is not being run.

When I add the data outside of the subscription it works fine.  Any ideas why this might be the case?

`                    <generic-table #homeTable [gtTexts]="{tableInfo:'#recordFrom - #recordTo of #recordsAfterSearch rows'}" [gtClasses]="'table-hover table-responsive table-bordered table-sm table-striped table-fixed'"
                      [gtSettings]="configObject.settings" [gtFields]="configObject.fields" [gtData]="configObject.data" [gtOptions]="{numberOfRows:20}"></generic-table>`

`this.data = [];
    this.configObject = {
      settings: BucketTables.InitiatedAll.getBaseSettings(),
      fields: BucketTables.InitiatedAll.getBaseFields(),
      data: this.data
    };`

Doesn't perform the render function:
`    this.busy = this.birthRecordService.getBirthRecordsByBucket(role, '').subscribe(result => {
      for (let i = 0; i < result.length; i++) {
        const row: any = {
          'id': result[i].recordID,
          'status': '',
          'aging': '0',
          'recordType': '',
          'mother': '',
          'childDob': '99/99/9999',
          'child': '',
          'sex': 'M',
          'plurality': 'Single',
          'bornAt': 'Fake Hospital 123',
          'maritalStatus': 'Not Married',
          'cop': 'M & F',
          'createdDate': '',
          'modifiedBy': '',
          'modifiedDate': ''
        };
        this.data.push(row);
      }
    });`

To fix it, I was able to add an empty object to `this.data` outside of the subscription. Basically I had to add a hidden row then it allows me to add the other rows with the correct rendering.

**Comment by hjalmers** [comment]
Hmm okay the reason it’s not working as expected is because you’re pushing data to the data array and the table pretty much treats it as an immutable array so instead you should replace the whole content with your new array. If you for some reason would like to keep the old data you could use the spread syntax like this:

```ts
this.data = [...this.data, newData];
```

`newData` should be an array with the data you want to add. Sorry for the short post but I’m on my phone and it’s a bit hard to elaborate the code without a proper screen and keyboard :S but it should give you and idea at least:)

**Comment by jackjamieson** [comment]
Ahhh I see, I set the config object to just `data: []` and pushed to `this.data` in the subscription, then did `this.configObject.data = this.data;`  and that works fine.  Thanks for the help!
