### ISSUE TITLE
How to get rowData when you click on particular row ?

### ISSUE THREAD

**Issue by Syedgit** [hjalmers/angular-generic-table#177]
I see the docs where you specify (gtEvent)="trigger($event) i could not get the row data using that event, I want to emit data by clicking on row or any feature that supports that please provide. 

Thanks
```
  <div class="table-responsive">
    <generic-table [gtClasses]="'table-hover'" #myCustomTable [gtSettings]="secondConfigObject.settings" (click)="selectedRow($event)" [gtFields]="secondConfigObject.fields" [gtData]="secondConfigObject.data"></generic-table>
  </div>
```

**Comment by hjalmers** [comment]
@Syedgit currently it's not possible to trigger events on row click unless you enable `rowSelection` ([see](https://github.com/hjalmers/angular-generic-table/wiki/Options)) and listen for `gt-row-select` and/or `gt-row-deselect` events. Another option would be to declare a click function in field settings and emit your own event or just execute a function, call a service or whatever you want to do when a cell/column is clicked.

It might be that we should add row click as an event though...

**Comment by Syedgit** [comment]
Can you please provide an example with gtOptions how to achieve this task also I would highly recommend you to add rowClick event that will be very helpful if you want to emit data from one data table to another.

**Comment by Syedgit** [comment]
i tried gtEvent i am getting the row event with below code but its send object even when you click on column labels and column setting, Any correct approach please gettign stuck here ...


component.ts

```
public trigger($event){
        this.detailService.changeObject($event.value.changedRow);
    }
```

component.html

   ` <generic-table [gtClasses]="'table-hover'" #myCustomTable [gtSettings]="secondConfigObject.settings" [gtFields]="secondConfigObject.fields" [gtData]="secondConfigObject.data" (gtEvent)="trigger($event)" [gtOptions]="{ rowSelection:true}"></generic-table>`
