### ISSUE TITLE
How can i update the table value?

### ISSUE THREAD

**Issue by jmblank09** [hjalmers/angular-generic-table#188]
My update is not reflecting on the table When i updated the data object in the configobject in the constructor. 

<img width="598" alt="screen shot 2018-01-28 at 2 15 32 pm" src="https://user-images.githubusercontent.com/21171734/35479570-c8e9e382-0435-11e8-952d-6e0e2b7df0d5.png">
<img width="621" alt="screen shot 2018-01-28 at 2 15 48 pm" src="https://user-images.githubusercontent.com/21171734/35479575-f00e3d1e-0435-11e8-9111-58b8082f6930.png">

**Comment by Crash1988** [comment]
Hi @jmblank09 , im not sure but you could try calling the table objet to redraw, in your class you can have a field like this: 
`@ViewChild(GenericTableComponent)
  private myTable: GenericTableComponent<any, any>;`

then after you update your data objet try calling redraw:
`this.myTable.redraw();`
please let me know if that help you, again i am not sure , just trying to help...

**Comment by jmblank09** [comment]
Thank you! It worked!

**Comment by jmblank09** [comment]
Last question. Is It possible to change the width style of a specific column. Also, when i add a long text, the text is overlapping other column.

![screen shot 2018-01-30 at 2 25 53 pm](https://user-images.githubusercontent.com/21171734/35551327-89337b5a-05c9-11e8-8a84-efe1843de097.png)

**Comment by Crash1988** [comment]
hi @jmblank09  i am sorry i have been very busy this week, you can add custom css using the special selectors for angular  :hot ::ng-deep so lets say you have a colum with class description-colum
```
:host ::ng-deep tr >  td.description-column {
  width: 200px;
}
```
that should work, although i think there is a better way, just i haven check the documentation yet
Thanks
