### ISSUE TITLE
Render is showing before the setting the data

### ISSUE THREAD

**Issue by jmblank09** [hjalmers/angular-generic-table#197]
![screen shot 2018-02-14 at 3 46 57 pm](https://user-images.githubusercontent.com/21171734/36193029-2c905486-119f-11e8-8168-f5997c20060b.png)

the render function is not waiting for the data to be set.

**Comment by sahilkatia** [comment]
@jmblank09  From the error, I can understand its not properly taking the values of fields.
Is it possible for you to post the code here?

**Comment by hjalmers** [comment]
It's probably an easy fix but like @sahilkatia said, would it be possible for you to post your set up here?

**Comment by jmblank09** [comment]
Already fixed. I first make the settings empty then assign it after getting the data
