### ISSUE TITLE
No way to disable standard sorting by first column

### ISSUE THREAD

**Issue by beerran** [hjalmers/angular-generic-table#230]
There is currently no way to disable the standard sorting on the first column.
Currently using a workaround by adding $$gtRowId to gtFields and gtSettings (hidden) and sorting by that key, as the index is correct.
Afterwards, we remove it from the genericTable that's being sent into GtColumnSettings to hide it from the user when toggling column order/visibility.

**Comment by hjalmers** [comment]
@beerran the last release v4.14.0 should fix this. The table now uses the original sort order of the data array initially and when sorting is applied it goes from enabled (original) => ascending => descending and then back to the original sort order if unsorted.
