### ISSUE TITLE
Update package-lock.json

### ISSUE THREAD

**Issue by mklein994** [hjalmers/angular-generic-table#239]
The package-lock.json file is different after running `npm install`.

**Comment by mklein994** [comment]
@hjalmers what version of `npm` are you using?

**Comment by hjalmers** [comment]
@mklein994 at work I'm using 5.10.0 and on my own computer I use 6.0.0. it's been a while since I updated so I should probably see what I'm missing out on from the latest version:)

**Comment by mklein994** [comment]
It's just that from what I've experimented with, the different versions of npm produce different `package-lock.json` files.

**Comment by hjalmers** [comment]
Yeah I've noticed it too, I ran `npm audit` and bumped some third-party dependencies that had vulnerabilities which affected the lock-file as well.
