### ISSUE TITLE
Lazy load example not using `lazyLoad` option

### ISSUE THREAD

**Issue by mklein994** [hjalmers/angular-generic-table#240]
Is there a reason the new example for lazy loading doesn't set `[gtOptions]="{lazyLoad: true}"`? I was experimenting with it (trying to get lazy loading to work with #221), and noticed that while the older one sets it, the new one doesn't.

---
Old:
https://github.com/hjalmers/angular-generic-table/blob/b824fa618c2afd41211654a7e47a32a9124a655c/src/app/lazy/lazy.component.html#L25
New:
https://github.com/hjalmers/angular-generic-table/blob/b824fa618c2afd41211654a7e47a32a9124a655c/src/app/examples/loading-data/lazy-load/lazy-load-example.component.html#L1-L6

**Comment by hjalmers** [comment]
It’s not finished yet so the old one is actually more correct. I just added the files to test the navigation between the examples and the loading of the raw files:)
