### ISSUE TITLE
how to provide fix height and width to table.

### ISSUE THREAD

**Issue by hinguabhishek** [hjalmers/angular-generic-table#243]

**Comment by hjalmers** [comment]
Maybe you could elaborate a little what you mean with fixed height? Currently the table doesn’t support internal scrolling or in other words the ability to set a fixed height together with a sticky header. However you can adjuste the row height using pure css and just set the number of rows to be displayed together with pagination. Same goes for the width. Each column will get a unique class name that you can use to set the width either in pixels or percent, it’s also possible to use the text-overflow property in css to truncate the table contents to force the table to use a certain width. Not sure if that answers your question?

**Comment by hjalmers** [comment]
I've created a separate issue for it here #247 as I think this is something the table should support and I actually had it working in another branch a long time ago. Can't promise when I'll have time to look at it again though...
