### ISSUE TITLE
Translate text 'PRESS ENTER TO SAVE' 

### ISSUE THREAD

**Issue by mayraGL** [hjalmers/angular-generic-table#249]
Hello! I would like to know if there is a way to translate the text 'PRESS ENTER TO SAVE' that is displayed when a field is being edited and has not been saved. 

![image](https://user-images.githubusercontent.com/29493115/40624759-0819cfee-6274-11e8-88a1-8b8151088ebc.png)

this is my method to translate the texts but the property inlineEditEdited is not working

![image](https://user-images.githubusercontent.com/29493115/40625242-dfa492e4-6276-11e8-88b5-4315e2bf73b7.png)

thanks

**Comment by hjalmers** [comment]
Hi, I noticed the property was missing from documentation so I've added it [here](https://github.com/hjalmers/angular-generic-table/wiki/Change-texts) now. It works for me but there might be some issues regarding usage together with promises, do the other texts work?

**Comment by mayraGL** [comment]
Yes, you are correct, I was incorrectly using the promise.

This is the right way to do it

![image](https://user-images.githubusercontent.com/29493115/40802095-4871ab3a-64da-11e8-9236-69f883e6e862.png)

**Comment by hjalmers** [comment]
It should probably support promises and/observables too, but in the meantime you'll have to handle it like you just did:)
