### ISSUE TITLE
How to customize sorting on column ? 

### ISSUE THREAD

**Issue by LokeshBoran** [hjalmers/angular-generic-table#250]
By default, sorting is working as `(default)=>(asc)=>(desc)=>(default)` manner. And in the documentation there is no way to modify sorting default behavior. Like if I want `(asc)=>(desc)=>(asc)`, How to achive it ?

**Comment by hjalmers** [comment]
So if I understand you correctly you don't want it to be possible to go back to an unsorted state? You can set the initial sort order but a few releases ago I removed the requirement to have the table always being sorted on something so now it will go back to the initial state (although I guess that could be a setting too).

**Comment by LokeshBoran** [comment]
Yes like other libraries there should be a setting for the same.

**Comment by hjalmers** [comment]
I've added an [option](https://github.com/hjalmers/angular-generic-table/wiki/Options) called `allowUnsorted` which by default is `true`. If set to `false` sort will switch between ascending and descending were as `true` will go from descending to unsorted.
