### ISSUE TITLE
Cannot install peer dependancies when installing on angular 5

### ISSUE THREAD

**Issue by niharankaha** [hjalmers/angular-generic-table#252]
Hey,

I have never used this plugin before and I tried to install via the command:
npm install @angular-generic-table/core --save

But don't know why the installation dependencies and I get the following warning(s)

npm WARN @angular-generic-table/core@4.15.0 requires a peer of @angular/core@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular-generic-table/core@4.15.0 requires a peer of @angular/common@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular-generic-table/core@4.15.0 requires a peer of @types/tether@^1.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN @angular-generic-table/core@4.15.0 requires a peer of tether@^1.4.0 but none is installed. You must install peer dependencies yourself.

Don't why the plugin is not installing the dependenices by itself, Any help will be appreciated.

Thanks!

**Comment by hjalmers** [comment]
I guess you figured it out since you closed the ticket? Peer dependencies aren’t actually installed so some of them might need to be installed separately depending on the other packages you’ve already installed. My feelings about using peer dependencies are a bit mixed as it’s confusing sometimes what dependencies you really need.

**Comment by niharankaha** [comment]
Yeah  installed the peer dependencies like tether. Yeah I understand the problems peer dependencies can cause like sometimes you may be clueless what to install. Thankfully the issue got solved and I like the plugin alot! Thanks for this!
