### ISSUE TITLE
Rendering table changes the original object

### ISSUE THREAD

**Issue by harryy2510** [hjalmers/angular-generic-table#263]
I am using generic table with @ngrx/store. Data subscribed from store when passed to config object is changed mutated with $$gtRowId and since the referenced directly from store, changes can be observed in store too. If I add an extra key to the config object, that is too mutated upto the store.

Can we make a copy of the data before mutating it?

**Comment by hjalmers** [comment]
This has been on my to-do list for some time now and ngrx is definitely something generic table should support. I'm not fond of the way the table is manipulating the data now and there's a plan to change it but it also means rewriting a lot from scratch. Angular has also evolved over the years so there are a lot of things that could be simplified and improved if the table would be rebuilt from scratch.

I'm afraid it's not as simple as just coping the data before manipulating but I've created a milestone and added this issue to it. We have a project at work that needs this too so I hope I'll get some help implementing full support for ngrx.

**Comment by harryy2510** [comment]
To know the issue further, Can you please tell me what all things will get affected if we try to create a deep copy of the data provided in the table?
As while providing data to the table, I myself create a deep copy of data. So how would the behavior of the table will get affected if the copy is made as soon as data is provided to the table?

**Comment by harryy2510** [comment]
Sure! let me give it a try.

**Comment by harryy2510** [comment]
The code needs a lot of change if moving to an immutable pattern. I've updated the initial cloning of data for now. Will try making changes to pipes too.

**Comment by hjalmers** [comment]
Thanks for contributing @harryy2510, the option for deep copying the initial data before manipulating the objects is now available with the release of v4.17.0 and I've added the option to the [wiki](https://github.com/hjalmers/angular-generic-table/wiki/Options) as well.
