### ISSUE TITLE
Angular 6 support?

### ISSUE THREAD

**Issue by rolphes** [hjalmers/angular-generic-table#266]
Hi there

Are there any plans to support Angular 6?

Regards
Rolf

**Comment by hjalmers** [comment]
@rolphes of course! Meanwhile you can get it working by installing `rxjs-compat` and `tether`:

```
npm install rxjs-compat tether
```
There's also some more info and a link to an example using angular 6 here #253

**Comment by hjalmers** [comment]
#253
