### ISSUE TITLE
Edit cell no detected

### ISSUE THREAD

**Issue by mayraGL** [hjalmers/angular-generic-table#269]
Hello @hjalmers 

I have the following table. When I write the first value in the first row and then move to the next row by pressing TAB I write quickly and then press TAB again, the cell does not detect that a change was made and does not save the value that was edited. This only happens when you type quickly and go to the next row with the TAB key. In my case I wrote 1 and press TAB again and again.

Please I hope you can help me

![image](https://user-images.githubusercontent.com/29493115/42962981-9949997e-8b58-11e8-9936-8b3a6fe0b444.png)

**Comment by hjalmers** [comment]
Sounds like it might be a bug, I don’t have access to a computer right now and won’t be able to replicate it and take a look for another week but I’ll mark it as a possible bug for now:)

**Comment by mayraGL** [comment]
Thanks @hjalmers

**Comment by hjalmers** [comment]
I found and fixed the issue. It will be part of the next release:)

**Comment by mayraGL** [comment]
Thanks @hjalmers

**Comment by mayraGL** [comment]
Hi @hjalmers 

Do you know when you will do the next update with the bug fixed?

**Comment by hjalmers** [comment]
Sorry for the delay @mayraGL but I've created a new version with the fix now so it's part of 4.17.1:)

**Comment by mayraGL** [comment]
Thanks @hjalmers 👍
