### ISSUE TITLE
Sorting is not working...

### ISSUE THREAD

**Issue by rcanpahali** [hjalmers/angular-generic-table#272]
Hello, my code is below:

`        <div class="col-lg-12">
            <generic-table #table1 [gtSettings]="gt.settings" [gtClasses]="'small'" [gtInfo]="gt.info" [gtOptions]="gtOptions" [gtFields]="gt.fields" [(gtData)]="gt.data" (gtEvent)="trigger($event)"></generic-table>
            <ng-template [ngIf]="isLoading">
                <div class="text-center">
                    <h4><i class="fa fa-fw fa-spin fa-spinner"></i> Hesaplar listeleniyor...</h4>
                </div>
            </ng-template>
            <div class="text-center">
                <gt-pagination [gtClasses]="'justify-content-center'" [genericTable]="table1"></gt-pagination>
            </div>
        </div>`

And i enabled sorting for this column:

`        {
          objectKey: 'accNo',
          sort: 'enable',
          columnOrder: 1
        },`

When I click on column, I console log the $event:

![image](https://user-images.githubusercontent.com/32385891/43395704-a82e1192-9407-11e8-8dc9-9a3d109cf782.png)

It seems like something happening but no change in my table.

I'm doing something wrong but don't know the reason.
Thanks.

**Comment by Liahus3003** [comment]
I am facing this same issue as well, we are getting $$gtInitialRowIndex as the event for 3rd click,
**Expected**  accNo -> -accNo -> accNo
**Actual** : accNo -> -accNo -> $$gtInitialRowIndex

**Comment by hjalmers** [comment]
@Liahus3003 check #250, since 4.16 it’s possible to configure the sorting behavior using `allowUnsorted` option.
