### ISSUE TITLE
Error upgrading to V4.17.1

### ISSUE THREAD

**Issue by brampeirs** [hjalmers/angular-generic-table#286]
I get an error when upgrading to V4.17.1

`ERROR in Metadata version mismatch for module /node_modules/@angular-generic-table/core/angular-generic-table-core.d.ts, found version 4, expected 3, resolving symbol ...`

Using Angular 4.4.6

**Comment by brampeirs** [comment]
@hjalmers we currently use V4.11.1 with metadata V3 
we use node version V6.4.0

We tried removing the lock file and node_modules, but this did not work.

**Comment by hjalmers** [comment]
Glad to hear you managed to solve the issue:)
