### ISSUE TITLE
Sorting on alphanumeric values 

### ISSUE THREAD

**Issue by manrav2508** [hjalmers/angular-generic-table#303]
I have alphanumeric value on a column data, eg Order No. OR-1, OR-2,OR-3..so on, I want to apply sorting on the same.

**Comment by hjalmers** [comment]
Hi @manrav2508 and sorry for the late reply. Not sure if this is still an issue for you or if you managed to solve it but the sort property in the [field configuration](https://github.com/hjalmers/angular-generic-table/wiki/Configuration) can be used for this.

Ex. if you want `No. OR-1`, `No. OR-2` and `No. OR-3` to be sorted like regular numbers you could use something like this: 

```js
sort: row => +row.orderNo.replace(/No. OR-/, '')
```

This would turn you string into a number and it would be sorted like a numeric instead.
