### ISSUE TITLE
Allow different expanding components for each column

### ISSUE THREAD

**Issue by hjalmers** [hjalmers/angular-generic-table#34]
Move gtRowComponent from input to expand function of gtFields

**Comment by jonaslalin** [comment]
We already support custom column components (see issue #44), should be trivial to support custom expandable row components for each column as well.

**Comment by hjalmers** [comment]
Support added in v4.7.0

Replace `input GtExpandedRow` and field config `expand: true`

with:

```js
expand: {
          component: CustomRowComponent
        }
```

[See live example](https://hjalmers.github.io/angular-generic-table/advanced)
