### ISSUE TITLE
Lazy table does not have consistent history of sorted columns between it and default table config

### ISSUE THREAD

**Issue by msut-s** [hjalmers/angular-generic-table#50]
Table config and table have inconsistent history of sorted columns.

E.g. if table config has a column set default on ascending, then when a user clicks to sort the same column in descending order an event with value `columnName` is returned instead of `-columnName`.
Seems to be affected by `table.sortOrder` variable being empty when the sort click is received.

**Comment by hjalmers** [comment]
I haven't really looked into this but I guess this is still an issue right? And it only happens if you try to sort a column that has been set to ascending by default? I look into it:)

**Comment by msut-s** [comment]
Yes, the issue of not having sorted history is present.
On the on the demo page: https://hjalmers.github.io/angular-generic-table/examples#lazy if you hold CTRL and click on another column - the first sorted column caret disappears.
