### ISSUE TITLE
Custom columnComponent does not work with lazy loading

### ISSUE THREAD

**Issue by albrechta** [hjalmers/angular-generic-table#54]
Is it possible to use a custom column component (columnComponent property) in combination with lazy loading?

I experimented with the [custom columns](https://hjalmers.github.io/angular2-generic-table/examples#custom) example and switched to lazy loading. After that, the custom column template is not used anymore (just the plain string is set).

**Comment by hjalmers** [comment]
It should work, but I'll have to look into it. Have you tried using custom columns together with lazy loading @jonaslalin?

**Comment by albrechta** [comment]
I just found out that there is a closed issue (#45) regarding custom columns and async loading, but it is not included in the current release yet. I hope you can release this fix soon.

Thanks for this nice lib.

**Comment by hjalmers** [comment]
This should be fixed in v1.1.1 which is published now.
