### ISSUE TITLE
Clarifying license

### ISSUE THREAD

**Issue by d-damien** [hjalmers/angular-generic-table#55]
Hello,

Could you please add a license file to ease the use of your software in other projects ?

~~For a lib / component like this, I would recommend MIT. https://choosealicense.com/~~

Edit : I should have looked in package.json.

Thank you for Generic Table.

**Comment by hjalmers** [comment]
Yeah I totally agree that it could be clarified, I'll add it as part of the source code:)

**Comment by d-damien** [comment]
I guess we can close it now.
