### ISSUE TITLE
Sort default 'enable' value is not being applied

### ISSUE THREAD

**Issue by msut-s** [hjalmers/angular-generic-table#71]
See https://hjalmers.github.io/angular-generic-table/examples#custom example.

Columns `name` and `age` do not have 'sort' property set as `enable`, therefore when the mouse hovers over the column header it does not change to a pointer. As well as the sort caret is not being applied when the column header is clicked.
However documentation states that 'sort' is optional with the default value `enable`.

**Comment by hjalmers** [comment]
Another good observation @msut-s, I'll make sure this is fixed:)
