### ISSUE TITLE
Examples 404 error

### ISSUE THREAD

**Issue by joandvgv** [hjalmers/angular-generic-table#75]
Hi! I want to use this component for my project, but I can't since examples site is broken.
Is there a way to run the examples locally?

**Comment by hjalmers** [comment]
Which URL are you using, might be an old reference? The example works for
me: https://hjalmers.github.io/angular-generic-table/
fre 14 apr. 2017 kl. 20:54 skrev Joan Gil <notifications@github.com>:

**Comment by joandvgv** [comment]
Hi! Thanks! It works.
My apologies. Maybe I was using an old version link I encountered on npm site.
