### ISSUE TITLE
GtExpandedRow is missing from declarations in core module

### ISSUE THREAD

**Issue by jackjamieson** [hjalmers/angular-generic-table#82]
The table cannot be loaded because of the following error:
` Can't export value GtExpandedRow from GenericTableModule as it was neither declared nor imported!`

`GtExpandedRow` also needs the `@Component` decorator to be used in the declaration.

**Comment by hjalmers** [comment]
Hi, sorry for the late reply I belive this error is a result of a bad package published to npm (4.1.0-rc.3 release). Just realized now when I looked at npm that the last versions have only been published to a private npm registry, fixed it now and added `https://registry.npmjs.org/` as default registry to avoid this in the future. Please update to latest version 4.1.1 and let me know it solves the issuse for you.

**Comment by jackjamieson** [comment]
No problem.  Yes that seems to have been the issue thank you.
