### ISSUE TITLE
Passing data to colmumnComponent?

### ISSUE THREAD

**Issue by jackjamieson** [hjalmers/angular-generic-table#86]
Is it possible to pass data into columnComponent from the parent?  For example, pulling options for a select once and passing that data into the component rather than having the component itself keep pulling that information for each row.

**Comment by hjalmers** [comment]
Sorry for the late reply...

Perhaps you could clarify a bit what you're trying to do? If you just want to be able to change the value in a cell using a dropdown take a look at [this example](https://hjalmers.github.io/angular-generic-table/inline-editing) and the language column.

**Comment by dimi71** [comment]
I want to pass boolean to child using columnComponent. Is it possible?

**Comment by jackjamieson** [comment]
I used a service to communicate between the parent and child columnComponent to take care of this.
Parent downloads the data, childs consumes it.
