### ISSUE TITLE
Confusing paging controls when no results are present

### ISSUE THREAD

**Issue by msut-s** [hjalmers/angular-generic-table#87]
Navigate to: https://hjalmers.github.io/angular-generic-table/advanced
Input text into search field that produces 0 matches

Observe: confusing paging controls (« 1 … 0 »)

**Comment by hjalmers** [comment]
Yes it would probably make sense to hide the paging controls if the table contains no records.

**Comment by hjalmers** [comment]
when table contains no records pagination controls will now show "1" by default and the class 'no-data' will be applied to the gt-pagination to enable easy hiding using css for those who wish to hide the pagination all together when the table contains no records.
