### ISSUE TITLE
Is it possible to customize the css of the table header?

### ISSUE THREAD

**Issue by nponna** [hjalmers/angular-generic-table#88]
@hjalmers

**Comment by hjalmers** [comment]
Yes, the table headers will get the same class names as the columns in the table body and you can target them specifically using the the `thead` selector together with `th` e.g.

If you'd like the table headers to be blue with white text:

``` css
thead tr th {
    background: #0275d8;
    color: #fff;
}
```

However it's currently not possible to add specific classes only for the table headers, classes added to the field settings object using `classNames` will be added both to headers and row columns.

**Comment by nponna** [comment]
@hjalmers 
Thank you. That was useful.

**Comment by KozlovAV** [comment]
In me case styles was applied only when i use /deep/ clause in my component css. Like this:
`
/deep/ generic-table#myTable table thead tr th {  vertical-align: middle;  text-align: center;
}
`

**Comment by hjalmers** [comment]
@KozlovAV the /deep/ selector is deprecated https://angular.io/guide/component-styles, but I suggest moving styling of table headers to your global css file or perhaps turn view encapsulation off for the component where you add the styling. My guess is that you want to reuse the styling for you table and it doesn't really make any sense to encapsulate styles that you want to share between different components...

**Comment by KozlovAV** [comment]
Thank you.
