### ISSUE TITLE
CSV escaping

### ISSUE THREAD

**Issue by nponna** [hjalmers/angular-generic-table#89]
Is there a possibility to do CSV escaping? 
For eg: 
If this is a field "John Doe, CFA" in a table, I would like to see double quotes around the entire field so Excel will not break that field into two columns.
Note: Im specifying the delimiter in this case to be a comma: ","

**Comment by nponna** [comment]
@hjalmers

**Comment by hjalmers** [comment]
Currently it's not supported but it should be, so I'll make sure it's part of the next version:)

**Comment by hjalmers** [comment]
@nponna the fix will be part of next release:)

**Comment by nponna** [comment]
@hjalmers  Thank you :)
